### ISSUE TITLE
Panic when generating noise with a dimension size <= 2

### ISSUE THREAD

**Issue by drake-amz** [jackmott/rust-simd-noise#4]
simdnoise panics when asked to generate noise with a dimension of size <= 2. I've only tried this with the `get_2d_scaled_noise` function, but others should be checked for this as well. Ideally the library could handle any size down to 0, possibly by special-case falling back to the scalar implementation for such small sizes. But at least the code should `assert!` and document the input limitation.

Minimal reproduction:
```rust
extern crate simdnoise;

fn main() {
    simdnoise::get_2d_scaled_noise(0.0, 3, 0.0, 2, simdnoise::NoiseType::Normal { freq: 0.05 }, 0.0, 1.0);
}
```

Example panic:
```% RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/simdnoise-bug`
thread 'main' panicked at 'attempt to subtract with overflow', /Users/drakeat/.cargo/registry/src/github.com-1ecc6299db9ec823/simdnoise-2.3.3/src/shared.rs:144:16
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:463
   5: std::panicking::try::do_call
             at libstd/panicking.rs:350
   6: std::panicking::try::do_call
             at libstd/panicking.rs:328
   7: <&'a T as core::fmt::Display>::fmt
             at libcore/panicking.rs:71
   8: <&'a T as core::fmt::Display>::fmt
             at libcore/panicking.rs:51
   9: core::coresimd::x86::avx::_mm256_setzero_si256
             at /Users/drakeat/.cargo/registry/src/github.com-1ecc6299db9ec823/simdnoise-2.3.3/src/shared.rs:144
             at /Users/drakeat/.cargo/registry/src/github.com-1ecc6299db9ec823/simdnoise-2.3.3/src/avx2.rs:194
  10: core::coresimd::x86::avx::_mm256_setzero_si256
             at /Users/drakeat/.cargo/registry/src/github.com-1ecc6299db9ec823/simdnoise-2.3.3/src/lib.rs:267
  11: simdnoise_bug::main
             at src/main.rs:4
  12: std::rt::lang_start::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  13: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  14: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:105
  15: std::sys_common::bytestring::debug_fmt_bytestring
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  16: std::rt::lang_start
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  17: simdnoise_bug::main
```

**Comment by jackmott** [comment]
Thanks I'll check on this, shouldn't be happening. I suspect it is due to X being < vector_width actually rather than y being 2.

**Comment by jackmott** [comment]
fixed by 03e3d9c3727d5032b658c67e0b9e5130878bcc3a
This is now published to crates.io as 2.3.4
give it a try and if you confirm it is fixed I'll close the issue.

The issue was when the total amount of noise is < than the vector_width, the scaling function was failing.

Good catch!

**Comment by jackmott** [comment]
I've also added a test for this scenario.

**Comment by drake-amz** [comment]
I am no longer seeing the panic after upgrading to 2.3.4.

```
% cargo update
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating simdnoise v2.3.3 -> v2.3.4
% cargo run
 Downloading simdnoise v2.3.4
   Compiling simdnoise v2.3.4
   Compiling simdnoise-bug v0.1.0 (file:///Users/drakeat/projects/simdnoise-bug)
    Finished dev [unoptimized + debuginfo] target(s) in 22.24s
     Running `target/debug/simdnoise-bug`
```
(no output is good)

**Comment by jackmott** [comment]
great, thanks for the help. closing.
